apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "${clusterissuer}"
spec:
  acme:
    email : "${acme_email}"
    server: "${acme_server}"
    privateKeySecretRef:
      name: acme-cluster-issuer
    solvers:
    - selector:
        dnsZones: ["${dns_zone}"]
      dns01:
%{ if provider == "aws" ~}
        route53:
          hostedZoneID: "${zone_id}"
          region: "${aws_region}"
          accessKeyID: "${aws_access_key}"
          secretAccessKeySecretRef:
            name: "${secret_key}"
            key: secret_key
%{ endif ~}
%{ if provider == "rfc2136" ~}
        rfc2136:
          nameserver: "${rfc_server}"
          tsigKeyName: "${rfc_key_name}"
          tsigAlgorithm: "${rfc_alg}"
          tsigSecretSecretRef:
            name: "${secret_key}"
            key: secret_key
%{ endif ~}
